eTicketsProject/Models/Actor.cs
<<<<<<< HEAD
﻿using eTicketsProject.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace eTicketsProject.Models
{
    public class Actor : IEntityBase
=======
﻿using System.ComponentModel.DataAnnotations;

namespace eTicketsProject.Models
{
    public class Actor
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Profile Picture")]
        [Required(ErrorMessage = "Profile Picture is required !")]
        public string? ProfilePictureURL { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
<<<<<<< HEAD
        [Required(ErrorMessage = "Please enter Full Name !")]
        [StringLength(60, MinimumLength = 5, ErrorMessage = "Full name must be between 5 and 60 chars")]
        [Display(Name = "Full Name")]
        public string? FullName { get; set; }

        [MinLength(30, ErrorMessage = "Biography should contains at least 30 chars !")]
=======
        [Required(ErrorMessage ="Please enter Full Name !")]
        [StringLength(60, MinimumLength =5, ErrorMessage ="Full name must be between 5 and 60 chars")]
        [Display(Name = "Full Name")]
        public string? FullName { get; set; }

        [MinLength(30 , ErrorMessage ="Biography should contains at least 30 chars !")]
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
        [Required(ErrorMessage = "A Biography is required !")]
        [Display(Name = "Biography")]
        public string? Bio { get; set; }

        //Relationship ;
        public List<Actor_Movie>? Actors_Movies { get; set; }
    }
}

eTicketsProject/Controllers/ActorsController.cs
using eTicketsProject.Data;
using eTicketsProject.Data.Services;
using eTicketsProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace eTicketsProject.Controllers
{
    public class ActorsController : Controller
    {
<<<<<<< HEAD
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
=======
        private readonly IActorsServices _service;
        public ActorsController(IActorsServices service)
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        
        //Get: Actors/Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio ")] Actor actor)
        {
            if (!ModelState.IsValid) return View(actor);
            await _service.AddAsync(actor);
<<<<<<< HEAD

            return RedirectToAction(nameof(Details), new { id = actor.Id });
=======
            
            return RedirectToAction(nameof(Index));
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
        }

        //Get: Actors/Details/1
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }

        //Get: Actors/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
       
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio ")] Actor actor)
        {
            if (!ModelState.IsValid) return View(actor);
<<<<<<< HEAD
            if (id == actor.Id)
            {
                await _service.UpdateAsync(id, actor);
                return RedirectToAction(nameof(Details), new { id = actor.Id });
            }
            return View(actor);     
=======
            await _service.UpdateAsync(id, actor);
            return RedirectToAction(nameof(Index));
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
        }


        //Get: Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);

        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
          
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

eTicketsProject/Views/Actors/Create.cshtml
@*
    create actor
*@

@model Actor

@{
    ViewData["Title"] = "Add a new actor";
}
<div class="hero common-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">
                    <h1> Create Actor</h1>
                    <ul class="breadcumb">
                        <li class="active"><a href="#">Back</a></li>
<<<<<<< HEAD
                        <li> <span class="ion-ios-arrow-right"></span> Add New Actor</li>
=======
                        <li> <span class="ion-ios-arrow-right"></span> actor listing</li>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single movie_list">
    <div class="container">
        <div class="row ipad-width2">

            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="sidebar">
<<<<<<< HEAD
                    <div class="searh-form">                      
                        <form class="form-style-1" asp-action="Create">
                            <div asp-validation-summary="ModelOnly" style="color:red"></div>
=======
                    <div class="searh-form">
                        <h4 class="sb-title">Add a new movie</h4>
                        <form class="form-style-1" asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                            <div class="row">
                                <div class="col-md-12 form-it">
                                    <img id="ProfilePicturePreview" />
                                </div>
                                <div class="col-md-12 form-it">
                                    <label asp-for="ProfilePictureURL"></label>
                                    <input asp-for="ProfilePictureURL"/>
<<<<<<< HEAD
                                    <span asp-validation-for="ProfilePictureURL" style="color:red"></span>
=======
                                    <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                                </div>
                                <div class="col-md-12 form-it">
                                    <label asp-for="FullName">Actor Name</label>
                                    <input asp-for="FullName"/>
<<<<<<< HEAD
                                    <span asp-validation-for="FullName" style="color:red"></span>
=======
                                    <span asp-validation-for="FullName" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                                </div>
                                <div class="col-md-12 form-it">
                                    <label asp-for="Bio">Biography</label>
                                    <input asp-for="Bio"/>
<<<<<<< HEAD
                                    <span asp-validation-for="Bio" style="color:red"></span>
=======
                                    <span asp-validation-for="Bio" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                                </div>

                                <div class="form-group">                              
                                    <a asp-action="Index" class="redbtn" style="margin:15px; float:left">
                                        <i class="fa fa-rotate-back"></i>
                                        Show All
                                    </a>
                                    <input class="redbtn" type="submit" value="Save" style="margin:15px; float:right" />
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();

        })
        
        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();           
        })
    </script>
}

eTicketsProject/Views/Actors/Delete.cshtml
@*
    delete actor
*@

@model Actor

@{
    ViewData["Title"] = "Delete Actor";
}
<div class="hero common-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">
                    <h1> Delete Actor</h1>
                    <ul class="breadcumb">
                        <li class="active"><a href="#">Back</a></li>
                        <li> <span class="ion-ios-arrow-right"></span> actor removing</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single movie_list">
    <div class="container">
        <div class="row ipad-width2">

            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="sidebar">
                    <div class="searh-form">
                        <h4 class="sb-title">Delete confirmation for @Model.FullName</h4>
                        <div class="row" style="color: #abb7c4;">
                            <div class="col-md-12 form-it" style="display:flex; justify-content:center">
                                <img id="ProfilePicturePreview" />
                            </div>
                            <div class="col-md-12 form-it">
                                <label asp-for="ProfilePictureURL"></label>
                                <input asp-for="ProfilePictureURL" readonly />
<<<<<<< HEAD
                                <span asp-validation-for="ProfilePictureURL"></span>
=======
                                <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                            </div>
                            <div class="col-md-12 form-it">
                                <label asp-for="FullName"></label>
                                <input asp-for="FullName" readonly />
<<<<<<< HEAD
                                <span asp-validation-for="FullName"></span>
=======
                                <span asp-validation-for="FullName" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                            </div>
                            <div class="col-md-12 form-it">
                                <label asp-for="Bio"></label>
                                <input asp-for="Bio" readonly />
<<<<<<< HEAD
                                <span asp-validation-for="Bio" ></span>
=======
                                <span asp-validation-for="Bio" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                            </div>

                            <div class="form-group">
                                <form asp-action="Delete">
                                    <input type="hidden" asp-asp-for="Id" />
                                    <input class="redbtn" type="submit" value="Confirm" style="margin:15px; float:right" />
                                </form>
                                <a asp-action="Index" class="redbtn" style="margin:15px; float:left">
                                    <i class="fa fa-rotate-back"></i>
                                    Show All
                                </a>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();

        })

    </script>
}

eTicketsProject/Views/Actors/Details.cshtml
@*
   Actor details
*@

@model Actor

@{
    ViewData["Title"] = "Actors Details";
}

<div class="hero hero3">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- <h1> movie listing - list</h1>
                <ul class="breadcumb">
                    <li class="active"><a href="#">Home</a></li>
                    <li> <span class="ion-ios-arrow-right"></span> movie listing</li>
                </ul> -->
            </div>
        </div>
    </div>
</div>
<!-- celebrity single section-->

<div class="page-single movie-single cebleb-single">
    <div class="container">
        <div class="row ipad-width">
            <div class="col-md-4 col-sm-12 col-xs-12">
                <div class="mv-ceb">
                    <img src="@Html.DisplayFor(model => model.ProfilePictureURL)" alt="@Html.DisplayFor(model => model.FullName)">
                </div>
            </div>
            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="movie-single-ct">
                    <h1 class="bd-hd">@Html.DisplayFor(model => model.FullName)</h1>
                    <p class="ceb-single">Actor  |  Producer</p>
                    <div class="social-link cebsingle-socail">
                        <a href="#"><i class="ion-social-facebook"></i></a>
                        <a href="#"><i class="ion-social-twitter"></i></a>
                        <a href="#"><i class="ion-social-googleplus"></i></a>
                        <a href="#"><i class="ion-social-linkedin"></i></a>
                    </div>
                    <div class="movie-tabs">
                        <div class="tabs">
                            <ul class="tab-links tabs-mv">
                                <li class="active"><a href="#overviewceb">Overview</a></li>
                                <li><a href="#biography"> </a></li>
                                <li><a href="#mediaceb"></a></li>
                                <li><a href="#filmography"></a></li>
                            </ul>
                            <div class="tab-content">
                                <div id="overviewceb" class="tab active">
                                    <div class="row">
                                        <div class="col-md-8 col-sm-12 col-xs-12">
                                            <p>
                                                @Html.DisplayFor(model => model.Bio)
                                            </p>
<<<<<<< HEAD
                                            <div style="margin-top:100%; display:flex; justify-content:center">
=======
                                            <div class="form-group" style="margin-top:100%; display:flex; justify-content:center">                          
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                                                <a asp-action="Index" class="redbtn" style="margin:15px; float:left">
                                                    <i class="fa fa-rotate-back"></i>
                                                    Show All
                                                </a>
                                                <a asp-action="Delete" asp-route-id="@Model.Id" class="redbtn" style="margin:15px">
                                                    <i class="fa fa-trash"></i>
                                                    Delete
                                                </a>
                                                <a asp-action="Edit" asp-route-id="@Model.Id" class="redbtn" style="margin:15px; float:right">
                                                    <i class="fa fa-edit"></i>
                                                    Edit
                                                </a>
                                            </div>
                                        </div>

                                        <div class="col-md-4 col-xs-12 col-sm-12">
                                            <div class="sb-it">
                                                <h6>Fullname:  </h6>
                                                <p><a href="#">@Html.DisplayFor(model => model.FullName)</a></p>
                                            </div>
                                            <div class="sb-it">
                                                <h6>Date of Birth: </h6>
                                                <p>June 24, 1982</p>
                                            </div>
                                            <div class="sb-it">
                                                <h6>Country:  </h6>
                                                <p>Australian</p>
                                            </div>
                                            <div class="ads">
                                                <img src="~/images/uploads/ads1.png" alt="">
                                            </div>
<<<<<<< HEAD
                                        </div>
                                    </div>

                                </div>

=======
                                        </div>                    
                                    </div>
                     
                                </div>
                            
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- celebrity single section-->

eTicketsProject/Views/Actors/Edit.cshtml
@*
    edit actor
*@

@model Actor

@{
    ViewData["Title"] = "Edit actor";
}
<div class="hero common-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">
                    <h1> Update Actor</h1>
                    <ul class="breadcumb">
                        <li class="active"><a href="#">Back</a></li>
                        <li> <span class="ion-ios-arrow-right"></span> actor listing</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-single movie_list">
    <div class="container">
        <div class="row ipad-width2">

            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="sidebar">
<<<<<<< HEAD
                    <div class="searh-form">         
                        <form class="form-style-1" asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" style="color:red"></div>
=======
                    <div class="searh-form">
                        <h4 class="sb-title">Add a new movie</h4>
                        <form class="form-style-1" asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                            <div class="row">
                                <div class="col-md-12 form-it" style="display:flex; justify-content:center">
                                    <img id="ProfilePicturePreview" />
                                </div>
                                <div class="col-md-12 form-it">
                                    <label asp-for="ProfilePictureURL"></label>
                                    <input asp-for="ProfilePictureURL"/>
<<<<<<< HEAD
                                    <span asp-validation-for="ProfilePictureURL" style="color:red"></span>
=======
                                    <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                                </div>
                                <div class="col-md-12 form-it">
                                    <label asp-for="FullName"></label>
                                    <input asp-for="FullName"/>
<<<<<<< HEAD
                                    <span asp-validation-for="FullName" style="color:red"></span>
=======
                                    <span asp-validation-for="FullName" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                                </div>
                                <div class="col-md-12 form-it">
                                    <label asp-for="Bio"></label>
                                    <input asp-for="Bio"/>
<<<<<<< HEAD
                                    <span asp-validation-for="Bio" style="color:red"></span>
=======
                                    <span asp-validation-for="Bio" class="text-danger"></span>
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                                </div>

                                <div class="form-group">                              
                                    <a asp-action="Index" class="redbtn" style="margin:15px; float:left">
                                        <i class="fa fa-rotate-back"></i>
                                        Show All
                                    </a>
                                    <input class="redbtn" type="submit" value="Update" style="margin:15px; float:right" />
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();

        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

eTicketsProject/Views/Actors/Index.cshtml
@*
    Actor
*@

@model IEnumerable<Actor>

@{
    ViewData["Title"] = "List of Actors";
}
<div class="hero common-hero">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="hero-ct">
                    <h1>Actors</h1>
                    <ul class="breadcumb">
                        <li class="active"><a href="#">Home</a></li>
                        <li> <span class="ion-ios-arrow-right"></span> Actors listing</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- actors list section-->
<div class="page-single">
    <div class="container">
        <div class="row ipad-width2">
<<<<<<< HEAD
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div class="ceb-item-style-2">
                            <a asp-action="Details" asp-route-id="@item.Id"><img src="@item.ProfilePictureURL" alt="@item.FullName"></a>
                            <div class="ceb-infor">
                                <h2><a asp-action="Details" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.FullName )</a></h2> <br>
                                <span>actor, uk</span>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div style="float:right; margin-right:10px">
            <a asp-action="Create" class="redbtn">
=======
            @foreach (var item in Model)
            {
                <div class="col-md-3 col-sm-12 col-xs-12">
                    <div class="celebrity-items">
                        <div class="ceb-item">
                            <a asp-action="Details" asp-route-id ="@item.Id"><img src="@item.ProfilePictureURL" alt="@item.FullName"></a>
                            <div class="ceb-infor">
                                <h2><a asp-action="Details" asp-route-id ="@item.Id">@item.FullName</a></h2>
                                <span>actor</span>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div style="float:right; margin-right:10px">
            <a asp-controller="Actors" asp-action="Create" class="redbtn">
>>>>>>> 2dc6d8cf8efa28acac0a3b7359a0c3f2cd596130
                <i class="fa fa-circle-plus"></i>
                Add New
            </a>
        </div>
    </div>
</div>
<!-- end of actors section-->